packages: []
allowBuilds:
  better-sqlite3: true
  electron-winstaller: true
  esbuild: true
  msgpackr-extract: true
blockExoticSubdeps: true
minimumReleaseAge: 1440
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeStrict: true
